CREATE TABLE CLIENTS
(
CLIENT_ID INT PRIMARY KEY,
CNAME VARCHAR(40) NOT NULL,
ADDRESS VARCHAR(30),
EMAIL VARCHAR(30) UNIQUE,
PHONE INT,
BUSINESS VARCHAR(20) NOT NULL
);

CREATE TABLE DEPARTMENTS
(
 DEPTNO INT PRIMARY KEY,
 DNAME VARCHAR(15) NOT NULL,
 LOC VARCHAR(20)
); 

CREATE TABLE EMPLOYEES
(
 EMPNO INT PRIMARY KEY,
 ENAME VARCHAR(20) NOT NULL,
 JOB VARCHAR(15),
 SALARY INT CHECK(SALARY > 0),
 DEPTNO INT REFERENCES DEPARTMENTS(DEPTNO)
);

CREATE TABLE PROJECTS
(
PROJECT_ID INT PRIMARY KEY,
DESCR VARCHAR(30) NOT NULL,
START_DATE DATE,
PLANNED_END_DATE DATE,
ACTUAL_END_DATE DATE,
BUDGET INT CHECK(BUDGET > 0),
CLIENT_ID INT REFERENCES CLIENTS(CLIENT_ID)
);

CREATE TABLE PROJECTTASKS
(
PROJECT_ID INT REFERENCES PROJECTS(PROJECT_ID),
EMPNO INT REFERENCES EMPLOYEES(EMPNO),
START_DATE DATE,
TASK VARCHAR(25) NOT NULL,
STATUS VARCHAR(15) NOT NULL
);

INSERT INTO CLIENTS
(CLIENT_ID,CNAME,ADDRESS,EMAIL,PHONE,BUSINESS)
VALUES
(1001,'ACME Utilities','Noida','contact@acmeutil.com',9567880032,'Manufacturing'),
(1002,'Trackon Consultants','Mumbai','consult@trackon.com',8734210090,'Consultant'),
(1003,'MoneySaver Distributors','Bangalore','save@moneysaver.com',7799886655,'Reseller'),
(1004,'Lawful Corp','Chennai','justice@lawful.com',9210342219,'Professional');

